export const PEER_STATES = {
    DISCONNECTED: 0,
    CONNECTING: 1,
    ACKNOWLEDGING_CONNECT: 2,
    CONNECTION_PENDING: 3,
    CONNECTION_SUCCEEDED: 4,
    CONNECTED: 5,
    DISCONNECT_LATER: 6,
    DISCONNECTING: 7,
    ACKNOWLEDGING_DISCONNECT: 8,
    ZOMBIE: 9,
} as const;
export type PEER_STATE = typeof PEER_STATES[keyof typeof PEER_STATES];
